title: Hian Kup Khoi
description: Learn Data Analysis in Lao Language
baseurl: ""
url: "https://hiankupkhoi.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
